import Link from "next/link";
const capabilities = [["Track any supported product", "Add Amazon, Flipkart, or Myntra listings and set your ideal price."], ["Compare verified offers", "See normalized products, current offers, and transparent price history."], ["Get the right alert", "Choose browser, email, SMS, or WhatsApp alerts with explicit opt-in."]];

/** Marketing landing page; authenticated dashboard routes can be added without changing domain code.
 * Sign-up redirects here (rather than straight into the dashboard) so the shopper signs in deliberately;
 * `registered=1` shows a one-time banner nudging them toward the sign-in page. */
export default async function HomePage({ searchParams }: { searchParams: Promise<{ registered?: string }> }) {
  const { registered } = await searchParams;
  return <main className="min-h-screen px-4 py-6 sm:px-8"><header className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="flex items-center gap-2 text-xl font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-600 text-white">P</span>Pricewise</Link><Link href="/auth/sign-in" className="btn-secondary">Sign in</Link></header>{registered && <div className="mx-auto mt-6 max-w-4xl rounded-xl border border-brand-200 bg-brand-50 px-4 py-3 text-center text-sm font-semibold text-brand-700">Account created! Please <Link href="/auth/sign-in" className="underline">sign in</Link> to continue.</div>}<section className="mx-auto max-w-4xl py-24 text-center sm:py-32"><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">PRIVATE BETA</span><h1 className="mt-6 text-5xl font-bold tracking-tight sm:text-7xl">Buy at the <span className="text-brand-600">right price.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Track verified prices, spot meaningful drops, and get intelligent help deciding when to buy.</p><div className="mt-9 flex justify-center gap-3"><Link href="/auth/sign-in" className="btn-primary">Start tracking</Link><Link href="/search" className="btn-secondary">Explore products</Link></div></section><section className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3" aria-label="Platform capabilities">{capabilities.map(([title, description]) => <article className="card p-6 text-left" key={title}><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</section></main>;
}
