import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";

export const metadata = { title: "Terms of Service | Pricewise" };

export default function TermsPage() {
  return (
    <div className="bg-surface">
      <SiteNav />
      <main className="page-enter pt-28">
        <section className="py-20">
          <div className="mx-auto max-w-3xl px-4 sm:px-8">
            <p className="label-caps text-brand-600">Legal</p>
            <h1 className="mt-2 text-4xl font-bold text-ink">Terms of Service</h1>
            <p className="mt-3 text-sm text-slate-500">Last updated: January 2026</p>

            <div className="card mt-10 space-y-8 p-8 sm:p-10">
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">1. Acceptance of terms</h2>
                <p className="leading-7 text-slate-600">
                  By creating a Pricewise account or using any part of the service, you agree to these terms. If you don&apos;t agree with them, please don&apos;t use the service.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">2. Using the service</h2>
                <p className="leading-7 text-slate-600">
                  Pricewise provides price comparison, AI-generated recommendations, review summaries, and related tools for personal, non-commercial use. Prices, availability, and specifications are sourced from third-party retailers and can change or be inaccurate - always confirm final details on the retailer&apos;s own site before purchasing.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">3. Your account</h2>
                <p className="leading-7 text-slate-600">
                  You&apos;re responsible for keeping your account credentials secure and for all activity under your account. Let us know immediately at <a href="mailto:hello@pricewise.app" className="font-semibold text-brand-700 hover:underline">hello@pricewise.app</a> if you suspect unauthorized access.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">4. AI-generated content</h2>
                <p className="leading-7 text-slate-600">
                  Recommendations, review summaries, and Shopping Chat answers are generated by AI models and are intended to help your research, not to serve as financial or professional advice. Always exercise your own judgment before making a purchase.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">5. Intellectual property</h2>
                <p className="leading-7 text-slate-600">
                  The Pricewise name, product, and design are owned by us. Product names, brand names, and retailer names referenced on the platform belong to their respective owners.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">6. Limitation of liability</h2>
                <p className="leading-7 text-slate-600">
                  Pricewise is provided &ldquo;as is.&rdquo; We work to keep pricing and product data accurate, but we aren&apos;t liable for losses arising from outdated prices, third-party retailer errors, or decisions made based on AI-generated content.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">7. Changes to these terms</h2>
                <p className="leading-7 text-slate-600">
                  We may update these terms occasionally. Continued use of the service after an update means you accept the revised terms.
                </p>
              </section>
              <section>
                <h2 className="mb-3 text-xl font-bold text-ink">8. Contact us</h2>
                <p className="leading-7 text-slate-600">
                  Questions about these terms can be sent to <a href="mailto:hello@pricewise.app" className="font-semibold text-brand-700 hover:underline">hello@pricewise.app</a>.
                </p>
              </section>
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
